### ISSUE TITLE
Text Hightlighting

### ISSUE THREAD

**Issue by vlyr** [gspasov/svelte-pdf-simple#4]
Is it possible to highlight text with the library? So for example a callback gets called when the user highlights text and gives you the text in the highlighted area.

Thanks for this great piece of software.

**Comment by gspasov** [comment]
I will take a look into this and see if there is something that could be done. 

PS. Sorry for late reply

**Comment by gspasov** [comment]
There might be a way to do this, yet it seems to be a little more involved than I currently have time for this.

From what I looked it seems that using `pdf-viewer` might be the solution, although it's not shipped with `pdf-dist` package and I'm not sure what is the correct way to integrate it / use it.

If someone give a more straight path on how to do this I'm willing to add it, but this investigation time is more than I'm currently willing to spend.
