### ISSUE TITLE
Missing pdf data source error

### ISSUE THREAD

**Issue by gdrose** [gspasov/svelte-pdf-simple#5]
(Sveltekit)

I copied the first example of the library:

```
<script lang="ts">
  import { PdfViewer } from "svelte-pdf-simple";
  const pathToPdf = "./example.pdf";
</script>

<PdfViewer url={pathToPdf} />

```

I switched up the pathToPdf to my path and I even tried moving it everywhere:
first I tried: `const pathToPdf = '$lib/assets/menu.pdf';`
then I tried: `const pathToPdf = 'src/lib/assets/menu.pdf';`
then I moved it inside the same directory of the route `const pathToPdf = './menu.pdf';`
I even tried to import the file directly: `import pdf from '$lib/assets/menu.pdf';`

But I always got a blank page rendered with this in the console:

![image](https://github.com/gspasov/svelte-pdf-simple/assets/63345060/76734f40-91b2-4347-8b50-1d8bc76b28fc)

And I don't know if it's useful but vs code throws the following error:

![image](https://github.com/gspasov/svelte-pdf-simple/assets/63345060/f03c4207-cfe5-428e-ac80-7bda1e5ac9f2)

It's probably 100% my fault, but honestly, I can't wrap my mind around this error. Thanks

**Comment by s00500** [comment]
Ran into the same issue today...

**Comment by gdrose** [comment]
I solved by doing the following:

**Comment by gdrose** [comment]
I solved it after a long headache by importing the library and binding the viewer in the onMount function:

```
<script>
	import { onMount } from 'svelte';
	let PdfViewer;
	import pdf from '$lib/assets/file.pdf';

	onMount(async () => {
		const module = await import('svelte-pdf');
		PdfViewer = module.default;
	});
</script>
	<svelte:component
		this={PdfViewer}
		url={pdf}
	/>
```
