### ISSUE TITLE
display multipage in one loading

### ISSUE THREAD

**Issue by Graciasjr** [gspasov/svelte-pdf-simple#7]
![mypdfviewer](https://github.com/gspasov/svelte-pdf-simple/assets/89590621/85ee6b38-1f6b-472e-91df-dc43c6af4061)

Hi, First to start, I would like to say that I love what you have created, it allows you to customize almost everything in the construction of a pdf viewer. 

However, I am encountering a size problem. I would like to replicate the native Chrome pdf viewer step by step in terms of UI and functionalities. I started but as you can see in the image, for the functionality of loading all the pages one after the other, I did something quite unproductive in terms of performance by iterating on the number of pages found to display all the pages in succession. Results, I find myself loading the component ```<PdfViewer props={path:URL}/> ```1*n (the number of pages found). I was wondering if there is a way to avoid loading components multiple time

![pdfviewer](https://github.com/gspasov/svelte-pdf-simple/assets/89590621/d8f37b67-24a4-4013-8d04-fb82bffbd79d)

**Comment by gspasov** [comment]
I understand your problem, but to me this is more of an implementation issue. It is not really a concern of this library to make it easier to make some specific implementation easier to achieve. I wanted to make this library as pure as possible without burdening users with implementation details that I have decided to use. 

I think that maybe the best solution for you here would be to fork this library and make the necessary changes that would make it easier for you to reach your desired implementation without having to render so many components.
